### ISSUE TITLE
Array API 2023 tracking issue

### ISSUE THREAD

**Issue by tomwhite** [cubed-dev/cubed#438]
This issue tracks the work needed to support [Python array API standard v2023.12](https://data-apis.org/array-api/2023.12/index.html).

The changes from the previous version are listed here: https://data-apis.org/array-api/2023.12/changelog.html#v2023-12

### elemwise
These should be straightforward to add.
- [x] [`clip`](https://data-apis.org/array-api/2023.12/API_specification/generated/array_api.clip.html)
- [x] [`copysign`](https://data-apis.org/array-api/2023.12/API_specification/generated/array_api.copysign.html)
- [x] [`hypot`](https://data-apis.org/array-api/2023.12/API_specification/generated/array_api.hypot.html)
- [x] [`maximum`](https://data-apis.org/array-api/2023.12/API_specification/generated/array_api.maximum.html)
- [x] [`minimum`](https://data-apis.org/array-api/2023.12/API_specification/generated/array_api.minimum.html)
- [x] [`signbit`](https://data-apis.org/array-api/2023.12/API_specification/generated/array_api.signbit.html)

### manipulation
- [x] [`repeat`](https://data-apis.org/array-api/2023.12/API_specification/generated/array_api.repeat.html)
- [x] [`tile`](https://data-apis.org/array-api/2023.12/API_specification/generated/array_api.tile.html)
- [x] [`unstack`](https://data-apis.org/array-api/2023.12/API_specification/generated/array_api.unstack.html)

### searching
- [x] [`searchsorted`](https://data-apis.org/array-api/2023.12/API_specification/generated/array_api.searchsorted.html)

### statistical
- [x] [`cumulative_sum`](https://data-apis.org/array-api/2023.12/API_specification/generated/array_api.cumulative_sum.html)
  - https://github.com/cubed-dev/cubed/issues/277

## Inspection APIs
- [x] [`__array_namespace_info__`](https://data-apis.org/array-api/2023.12/API_specification/inspection.html)

**Comment by hammer** [comment]
Is it worth creating a separate issue to track linalg and fft [extensions](https://data-apis.org/array-api/latest/extensions/index.html)? It would be useful to know the Cubed position on these functions as well.

**Comment by tomwhite** [comment]
Opened #675 and #676. See also https://github.com/cubed-dev/cubed/blob/main/api_status.md for current status.
